module.exports = function(text, boundaries) {
  var end, endIndex, endTag, i, index, len, offset, range, start, startIndex, startTag, word;
  startTag = '<mark>';
  endTag = '</mark>';
  for (index = i = 0, len = boundaries.length; i < len; index = ++i) {
    range = boundaries[index];
    if (index !== 0) {
      offset = (startTag.length + endTag.length) * index;
      startIndex = range[0] + offset;
      endIndex = range[1] + offset;
    } else {
      startIndex = range[0];
      endIndex = range[1];
    }
    start = text.slice(0, startIndex);
    word = text.slice(startIndex, endIndex);
    end = text.slice(endIndex);
    text = "" + start + startTag + word + endTag + end;
  }
  return text;
};

// ---
// generated by coffee-script 1.9.2
