// flow-typed signature: 5cc218c4d830cb34beb520dcd4da50ef
// flow-typed version: <<STUB>>/babel-plugin-istanbul_v3.0.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-istanbul'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-istanbul' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-istanbul/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-istanbul/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-istanbul/lib/index'>;
}
